version: '3.7'
services:
  postgres:
    env_file: 
      - .env
    image: postgres:latest
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - /data/postgres/
    networks:
      - otasoft-auth-network

networks: 
  otasoft-auth-network:
    driver: bridge